// <auto-generated />
using System;
using AstroTrack.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AstroTrack.Infrastructure.Data.Migrations.EfCore;

[DbContext(typeof(AstroTrackDbContext))]
partial class AstroTrackDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder mb)
    {
#pragma warning disable 612, 618
        mb
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(mb);

        mb.Entity("AstroTrack.Domain.Entities.Satellite", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Category").IsRequired().HasColumnType("text");
            b.Property<string>("Country").HasColumnType("text");
            b.Property<string>("DataSource").IsRequired().HasColumnType("text");
            b.Property<DateOnly?>("LaunchDate").HasColumnType("date");
            b.Property<DateTimeOffset>("LastUpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("MissionDescription").HasColumnType("text");
            b.Property<string>("Name").IsRequired().HasColumnType("text");
            b.Property<int>("NoradId").HasColumnType("integer");
            b.Property<string>("Operator").HasColumnType("text");
            b.Property<string>("OrbitType").HasColumnType("text");
            b.Property<string>("TleLine1").IsRequired().HasColumnType("text");
            b.Property<string>("TleLine2").IsRequired().HasColumnType("text");
            b.HasKey("Id");
            b.HasIndex("Category").HasDatabaseName("IX_satellites_Category");
            b.HasIndex("NoradId").IsUnique().HasDatabaseName("IX_satellites_NoradId");
            b.ToTable("satellites");
        });

        mb.Entity("AstroTrack.Domain.Entities.SatellitePosition", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<double>("AltitudeKm").HasColumnType("double precision");
            b.Property<double>("LatitudeDeg").HasColumnType("double precision");
            b.Property<double>("LongitudeDeg").HasColumnType("double precision");
            b.Property<Guid>("SatelliteId").HasColumnType("uuid");
            b.Property<DateTimeOffset>("Timestamp").HasColumnType("timestamp with time zone");
            b.Property<double>("VelocityKmS").HasColumnType("double precision");
            b.HasKey("Id");
            b.HasIndex("SatelliteId", "Timestamp").HasDatabaseName("IX_satellite_positions_SatelliteId_Timestamp");
            b.ToTable("satellite_positions");
        });

        mb.Entity("AstroTrack.Domain.Entities.UserProfile", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<double?>("DefaultLatitude").HasColumnType("double precision");
            b.Property<string>("DefaultCity").HasColumnType("text");
            b.Property<double?>("DefaultLongitude").HasColumnType("double precision");
            b.Property<string>("DisplayName").HasColumnType("text");
            b.Property<string>("Email").IsRequired().HasColumnType("text");
            b.HasKey("Id");
            b.HasIndex("Email").IsUnique().HasDatabaseName("IX_user_profiles_Email");
            b.ToTable("user_profiles");
        });

        mb.Entity("AstroTrack.Domain.Entities.UserFavorite", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<int>("NoradId").HasColumnType("integer");
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("UserId", "NoradId").IsUnique().HasDatabaseName("IX_user_favorites_UserId_NoradId");
            b.ToTable("user_favorites");
        });

        mb.Entity("AstroTrack.Domain.Entities.PassPrediction", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTimeOffset>("EndTime").HasColumnType("timestamp with time zone");
            b.Property<double>("MaxElevationDeg").HasColumnType("double precision");
            b.Property<int>("NoradId").HasColumnType("integer");
            b.Property<DateTimeOffset>("PeakTime").HasColumnType("timestamp with time zone");
            b.Property<double>("VisibilityScore").HasColumnType("double precision");
            b.Property<DateTimeOffset>("StartTime").HasColumnType("timestamp with time zone");
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("UserId", "StartTime").HasDatabaseName("IX_pass_predictions_UserId_StartTime");
            b.ToTable("pass_predictions");
        });
#pragma warning restore 612, 618
    }
}
